alter table TESTTASKTKACHEV_CAR_MODEL add constraint FK_TESTTASKTKACHEV_CAR_MODEL_ON_CAR foreign key (CAR_ID) references TESTTASKTKACHEV_CAR(ID);
create index IDX_TESTTASKTKACHEV_CAR_MODEL_ON_CAR on TESTTASKTKACHEV_CAR_MODEL (CAR_ID);
