alter table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION add column CAR_ID uuid ;
alter table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION add column INDIVIDUAL_PERSON_ID uuid ;
alter table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION add column BANK_ID uuid ;
