alter table TESTTASKTKACHEV_CAR add constraint FK_TESTTASKTKACHEV_CAR_ON_CAR_MODEL foreign key (CAR_MODEL_ID) references TESTTASKTKACHEV_CAR_MODEL(ID);
create index IDX_TESTTASKTKACHEV_CAR_ON_CAR_MODEL on TESTTASKTKACHEV_CAR (CAR_MODEL_ID);
