create table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_INDIVIDUAL_LINK (
    VEHICLE_PURCHASE_REQUISITION_ID uuid,
    INDIVIDUAL_ID uuid,
    primary key (VEHICLE_PURCHASE_REQUISITION_ID, INDIVIDUAL_ID)
);
