create table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_CAR_CARD_LINK (
    VEHICLE_PURCHASE_REQUISITION_ID uuid,
    CAR_CARD_ID uuid,
    primary key (VEHICLE_PURCHASE_REQUISITION_ID, CAR_CARD_ID)
);
