-- begin TESTTASKTKACHEV_CAR_MODEL
create table TESTTASKTKACHEV_CAR_MODEL (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    NAME varchar(250),
    CODE varchar(100),
    NOTE varchar(500),
    --
    primary key (ID)
)^
-- end TESTTASKTKACHEV_CAR_MODEL
-- begin TESTTASKTKACHEV_CAR_CARD
create table TESTTASKTKACHEV_CAR_CARD (
    CARD_ID uuid,
    --
    NUMBER_ varchar(50),
    CAR_TYPE varchar(50),
    NAME varchar(150),
    CAR_MODELS_ID uuid,
    YEAR_OF_RELEASE date,
    --
    primary key (CARD_ID)
)^
-- end TESTTASKTKACHEV_CAR_CARD
-- begin TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION
create table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION (
    CARD_ID uuid,
    --
    IS_PAY_CAR boolean,
    --
    primary key (CARD_ID)
)^
-- end TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION
-- begin TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_INDIVIDUAL_LINK
create table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_INDIVIDUAL_LINK (
    VEHICLE_PURCHASE_REQUISITION_ID uuid,
    INDIVIDUAL_ID uuid,
    primary key (VEHICLE_PURCHASE_REQUISITION_ID, INDIVIDUAL_ID)
)^
-- end TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_INDIVIDUAL_LINK
-- begin TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_CAR_CARD_LINK
create table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_CAR_CARD_LINK (
    VEHICLE_PURCHASE_REQUISITION_ID uuid,
    CAR_CARD_ID uuid,
    primary key (VEHICLE_PURCHASE_REQUISITION_ID, CAR_CARD_ID)
)^
-- end TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_CAR_CARD_LINK
-- begin TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_BANK_LINK
create table TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_BANK_LINK (
    VEHICLE_PURCHASE_REQUISITION_ID uuid,
    BANK_ID uuid,
    primary key (VEHICLE_PURCHASE_REQUISITION_ID, BANK_ID)
)^
-- end TESTTASKTKACHEV_VEHICLE_PURCHASE_REQUISITION_BANK_LINK
